### PR TITLE
feat: add parent attribute (#71)

### LINKED ISSUE #71: Get parent token
I've implemented a custom `HTMLRenderer`, where I want to know if `render_image` is the only element on a paragraph.

Essentially be able to differentiate the output between these:

```markdown
Foo ![](foobar.png) Bar

![](foobar.png)
```

This could be possible if `token` has a `parent` attribute.

```python
class TestRenderer(HTMLRenderer):
    def render_image(self, token):
        has_more = len(token.parent.children) > 1
        if has_more:
            ...
        else:
            ...
```

Currently I have a `_set_parent` function, that is applied to `Document` in `render`.
However it would be nice, if this was part of mistletoe and done as children are added to the token.

```python
from mistletoe import HTMLRenderer
from mistletoe.block_token import Document

def _set_parent(parent):
    if hasattr(parent, "children"):
        for child in parent.children:
            setattr(child, "parent", parent)
            _set_parent(child)

class TestRenderer(HTMLRenderer):
    def render(self, token):
        if isinstance(token, Document):
            _set_parent(token)
        return super().render(token)

    def render_image(self, token):
        has_more = len(token.parent.children) > 1
        ...
```

### PR DESCRIPTION
**Pull request by pbodnar**
This resolves #71 and is a continuation / replacement for PR #72.

### CODE REVIEW

**Comment by pbodnar** [comment]
I'm hopefully choosing the simplest solution for introducing this feature. By making both the `children` and `parent` attribute a `@property`, we can extend the existing code and centralize the solution without much refactoring - although the API won't remain fully backwards compatible (`hasattr(...)` needs to be replaced by `... is not None` etc.).

An alternative approach would possibly be to pass the `parent` to every token constructor up to the `Token` class, but if I'm not mistaken, this would require much more changes - which would newly require calling `super().__init__(...)` in all the token classes. And I'm not sure it is a good time for doing that now.

Another thing is the **performance penalty** - running the benchmark (`python test/benchmark.py mistletoe` or running it via [mprof](https://pypi.org/project/memory-profiler/) to also see memory usage) shows me that mistletoe gets 4% slower and uses +13% memory when recording the children's `parent`. These are not great results, OTOH 1) it shouldn't be of such a big deal nowadays, 2) it cannot be probably implemented in a more efficient way (or can it?), 3) all the other competing tools (markdown, commonmark and its "de-facto replacement" markdown-it-py) seem to record token's parent (with no option to turn this off).

All in all, if someone (like @anderskaplan? ;)) doesn't propose a better solution, I would finish this PR (adding some docs and updating the benchmark results (yes, we should automate running those benchmarks...)) and merge it to the master branch. I think this would nicely complement the recent PR #188...

**Comment by pbodnar** [comment]
I've decided to merge this into the master and update the benchmark results later on (there is more to update).

_Here are the COMPATIBILITY REMARKS:_

* As the `children` _attribute_ changed to _property_, existing code needs to be changed like this:
  ```diff
  -hasattr(token, 'children')
  +token.children is not None

  # ...
  
  -'children' in vars(token)
  +token.children is not None
  
  # ...
  
  -getattr(token, 'children', [])
  +token.children or []
  ```

**Comment by vallentin** [comment]
Hey, sorry for not coming back to this. But since this has been merged, then I guess we can close my PR #72? :)

**Comment by pbodnar** [comment]
@vallentin, you are right, thanks for the reminder. 👍

**Pull request merged**
