### PR TITLE
Added parent attribute

### LINKED ISSUE #71: Get parent token
I've implemented a custom `HTMLRenderer`, where I want to know if `render_image` is the only element on a paragraph.

Essentially be able to differentiate the output between these:

```markdown
Foo ![](foobar.png) Bar

![](foobar.png)
```

This could be possible if `token` has a `parent` attribute.

```python
class TestRenderer(HTMLRenderer):
    def render_image(self, token):
        has_more = len(token.parent.children) > 1
        if has_more:
            ...
        else:
            ...
```

Currently I have a `_set_parent` function, that is applied to `Document` in `render`.
However it would be nice, if this was part of mistletoe and done as children are added to the token.

```python
from mistletoe import HTMLRenderer
from mistletoe.block_token import Document

def _set_parent(parent):
    if hasattr(parent, "children"):
        for child in parent.children:
            setattr(child, "parent", parent)
            _set_parent(child)

class TestRenderer(HTMLRenderer):
    def render(self, token):
        if isinstance(token, Document):
            _set_parent(token)
        return super().render(token)

    def render_image(self, token):
        has_more = len(token.parent.children) > 1
        ...
```

### PR DESCRIPTION
**Pull request by vallentin**
Resolves #71.

### CODE REVIEW

**Comment by Vallentin** [comment]
*Here's a suggestion.*

Instead of all the `for child in children`, it might be beneficial to change `__init__` of `SpanToken` and `BlockToken`. To allow and instead pass all children via `super()`.

Something like:

```python
class SpanToken:
    ...

    def __init__(self, match, children=None):
        if not self.parse_inner:
            self.content = match.group(self.parse_group)
        if children is not None:
            self.children = children
            for child in self.children:
                child.parent = self

    def __contains__(self, text):
        if hasattr(self, 'children'):
            return any(text in child for child in self.children)
        return text in self.content
```

What do you think @miyuchina? Is the `parent` attribute even something you want in the first place?

**Comment by pbodnar** [comment]
This looks promising. I totally agree with some refactoring though, so that the logic of setting `parent` into `children` is kept just at one place.

**Comment by pbodnar** [comment]
Hi there, I would like to finally finish this feature after all the years. :) I think now, the simplest thing to do is to make the `children` attribute a `@property` with a setter function which would take care of setting the `parent` to all the `children`. Now that we've already got the common `Token` ancestor class, it would mean extending just this class. I will check this out and possibly create a fresh PR...

**Comment by pbodnar** [comment]
Replaced by #206. Thanks for the initial idea. :)

**Pull request closed without merging**
