### PR TITLE
Fix for #108, CommonMark 0.30 spec compliance, part 3

### PR DESCRIPTION
**Pull request by anderskaplan**
The third and final PR for this issue, fixing the last remaining test case.

### CODE REVIEW

**Comment by pbodnar** [comment]
@anderskaplan, great, I wouldn't probably fix this better, thank you. :)

I would just remove the `#` before `146` in the commit message, so that GitHub doesn't try to link the commit with an unrelated issue here.

**Comment by anderskaplan** [comment]
commit message updated

**Comment by anderskaplan** [comment]
commit message updated to reference the mistletoe ticket (#108)

**Comment by pbodnar** [comment]
Thank you!

**Pull request merged**
